apiVersion: v1
kind: ServiceAccount
metadata:
  name: iot-admin
  namespace: iot
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: role-rabbitmq
  namespace: iot
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rabbitmq
  namespace: iot
subjects:
- kind: ServiceAccount
  name: iot-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-rabbitmq