#for clustering, RabbitMQ uses port 4369 for port 4369 for node discovery and port 25672 for inter-node communication
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless-svc
  namespace: iot
spec:
  clusterIP: None
  ports:
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: cluster-links
    port: 25672
    protocol: TCP
    targetPort: 25672
  selector:
    app: rabbitmq
  type: ClusterIP
  sessionAffinity: None